CREATE TABLE menu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori VARCHAR(20),
    nama_menu VARCHAR(50),
    harga INT,
    deskripsi TEXT
);

INSERT INTO menu (kategori, nama_menu, harga, deskripsi) VALUES
('Coffee Based', 'Americano Arabica', 13000, 'Kopi hitam dengan rasa khas arabika.'),
('Coffee Based', 'Arabica Coffee Milk', 18000, 'Kopi arabika dengan tambahan susu yang creamy.'),
('Coffee Based', 'Arenga Coffee', 22000, 'Kopi dengan campuran gula aren yang manis.'),
('Coffee Based', 'Avocado Coffee', 32000, 'Kopi dengan rasa alpukat yang kaya dan creamy.'),
('Coffee Based', 'Black Sesame Coffee', 23000, 'Kopi dengan rasa wijen hitam yang unik.'),
('Coffee Based', 'Caffe Latte', 20000, 'Espresso dengan susu yang lembut.'),
('Coffee Based', 'Cappuccino', 22000, 'Kombinasi espresso, susu, dan foam lembut.'),
('Coffee Based', 'Cappuccino Cincau', 23000, 'Cappuccino dengan tambahan cincau yang segar.'),
('Coffee Based', 'Caramel Coffee', 28000, 'Kopi dengan rasa manis dari karamel.'),
('Coffee Based', 'Choco Coffee', 22000, 'Perpaduan kopi dan cokelat yang nikmat.'),
('Coffee Based', 'Classic Caffe Latte', 18000, 'Latte klasik dengan rasa lembut dan creamy.'),
('Coffee Based', 'Espresso Romano', 22000, 'Espresso dengan rasa citrus khas Romano.'),
('Coffee Based', 'Hazelnut Coffee Milk', 28000, 'Kopi susu dengan tambahan rasa hazelnut.'),
('Coffee Based', 'Long Black Robusta', 10000, 'Kopi hitam dari robusta dengan rasa kuat.'),
('Coffee Based', 'Oreo Coffee', 28000, 'Kopi dengan tambahan oreo yang renyah dan manis.'),
('Coffee Based', 'Robusta Coffee Milk', 15000, 'Kopi robusta dengan susu yang creamy.'),
('Coffee Based', 'Vanilla Coffee', 28000, 'Kopi dengan tambahan rasa vanilla yang harum.'),
('Non Coffee Based', 'Avocado Latte', 28000, 'Latte dengan campuran alpukat yang creamy.'),
('Non Coffee Based', 'Black Sesame Latte', 18000, 'Latte dengan rasa wijen hitam yang unik.'),
('Non Coffee Based', 'Brown Sugar Boba Milk', 21000, 'Susu dengan tambahan boba dan gula aren.'),
('Non Coffee Based', 'Choco Nut', 28000, 'Minuman cokelat dengan rasa kacang yang gurih.'),
('Non Coffee Based', 'Cookies N Cream', 26000, 'Minuman creamy dengan tambahan biskuit.'),
('Non Coffee Based', 'Matcha Boba Latte', 21000, 'Latte matcha dengan tambahan boba manis.'),
('Non Coffee Based', 'Milo Choco Chips', 25000, 'Minuman Milo dengan tambahan choco chips.'),
('Non Coffee Based', 'Milo Latte', 15000, 'Kombinasi Milo dengan latte yang creamy.'),
('Non Coffee Based', 'Strawberry Red Velvet', 28000, 'Minuman rasa red velvet dengan tambahan stroberi segar.'),
('Makanan', 'Cyber Fried Chicken', 18000, 'Ayam goreng crispy dengan saus spesial.'),
('Makanan', 'Chicken Steak', 28000, 'Steak ayam dengan saus pilihan.'),
('Makanan', 'Ebi Furai Omelette', 25000, 'Omelet dengan udang goreng renyah.'),
('Makanan', 'Beef Bulgogi', 35000, 'Daging sapi dengan bumbu bulgogi khas Korea.'),
('Makanan', 'Cyber Fried Noodle', 17000, 'Mie goreng dengan bumbu khas CW yang lezat.');